// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;
using Newtonsoft.Json;

namespace KenticoCloudContentManagementAPIFunctions.Models
{
    public partial class Article
    {
        [JsonProperty("title")]
        public string Title { get; set; }
        [JsonProperty("intro")]
        public string Intro { get; set; }

        [JsonProperty("body")]
        public string Body { get; set; }
    }
}